baseURL = "https://joelcrosby.dev"
languageCode = "en-us"
title = "joelcrosby.dev"
enableGitInfo = true

[params]
  Subtitle = "A Dev's note about things"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -110
  [[menu.main]]
    identifier = "netputune"
    name = "Netputune"
    url = "/projects/netptune"
    weight = -110

